name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # İstediğiniz Go sürümünü burada belirtebilirsiniz.

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/@latest

      - name: Run linter
        run: golangci-lint run ./...