
name: Go Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Run Go Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install golangci-lint
        run: GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/[email protected]
        
      - name: Run golangci-lint
        run: golangci-lint run ./...
