name: CI-MYSQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        mysql:
          image: mysql:latest
          env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER: ${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          ports:
            - localhost:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start MySQL container
      run: docker-compose up -d

    - name: Wait for MySQL to be ready
      run: docker-compose exec mysql bash -c 'while ! mysqladmin ping -h"localhost" --silent; do sleep 1; done'

    - name: Build
      run: go build

    - name: Test
      run: go test ./...
      